#ddev-generated
# ddev manages this file and may delete or overwrite it unless the above line is removed.
# This file comes from "ddev get julienloizelet/ddev-crowdsec-php"
services:
  crowdsec:
    image: crowdsecurity/crowdsec:latest
    cap_add:
      - NET_ADMIN
      - NET_RAW
    container_name: ddev-${DDEV_SITENAME}-crowdsec
    hostname: ${DDEV_SITENAME}-crowdsec
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
      - ".:/mnt/ddev_config"
      - ./okaeli-add-on/custom_files/crowdsec/acquis/appsec.yaml:/etc/crowdsec/acquis.d/appsec.yaml
      - ./okaeli-add-on/custom_files/crowdsec/appsec-rules/vpatch-testappsec.yaml:/etc/crowdsec/appsec-rules/vpatch-testappsec.yaml
      - crowdsec_data:/var/lib/crowdsec/data
    environment:
      - COLLECTIONS=crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-generic-rules
    ports:
      - "8080:8080"
      - "7422"
  web:
    links:
      - crowdsec:crowdsec

volumes:
  crowdsec_data:
