#ddev-generated
# ddev manages this file and may delete or overwrite it unless the above line is removed.
# This file comes from "ddev get julienloizelet/ddev-crowdsec-php"
version: '3.6'
services:
  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: ddev-${DDEV_SITENAME}-crowdsec
    hostname: ${DDEV_SITENAME}-crowdsec
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
      - ".:/mnt/ddev_config"
      - ./okaeli-add-on/custom_files/crowdsec/cfssl:/tmp/cfssl
      - ./okaeli-add-on/custom_files/crowdsec/custom-config.yaml:/etc/crowdsec/config.yaml.local
      - ./okaeli-add-on/custom_files/crowdsec/custom-local-api-credentials.yaml:/etc/crowdsec/local_api_credentials.yaml.local
      - ./okaeli-add-on/custom_files/crowdsec/acquis/appsec.yaml:/etc/crowdsec/acquis.d/appsec.yaml
    environment:
      - COLLECTIONS=crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-generic-rules
    ports:
      - "8080"
      - "7422"
  web:
    links:
      - crowdsec:crowdsec
