#!/usr/bin/env sh

#ddev-generated
# ddev manages this file and may delete or overwrite it unless the above line is removed.
# This file comes from "ddev get julienloizelet/ddev-crowdsec-php"

## Description: Create a bouncer and return bouncer key
## Usage: create-bouncer bouncerName
## Example: "ddev create-bouncer my-bouncer"


BOUNCER_NAME=${1:-my-bouncer}

EXIST=$(cscli bouncers list -o raw | { grep "${BOUNCER_NAME}" || true; })


if [ $EXIST ];
then
    cscli bouncers delete $BOUNCER_NAME -o raw
fi

echo $(cscli bouncers add $BOUNCER_NAME -o raw | sed 's/\r//g')
exit 0
