#!/usr/bin/env sh

#ddev-generated
# Remove the line above if you don't want this file to be overwritten
# when you run ddev get julienloizelet/ddev-crowdsec-php

## Description: Create a bouncer and return bouncer key
## Usage: create-bouncer bouncerName
## Example: "ddev create-bouncer my-bouncer"


BOUNCER_NAME=${1:-my-bouncer}

EXIST=$(cscli bouncers list -o raw | { grep "${BOUNCER_NAME}" || true; })


if [ $EXIST ];
then
    cscli bouncers delete $BOUNCER_NAME -o raw
fi

echo $(cscli bouncers add $BOUNCER_NAME -o raw | sed 's/\r//g')
exit 0
