#!/usr/bin/env sh

#ddev-generated
# Remove the line above if you don't want this file to be overwritten
# when you run ddev get julienloizelet/ddev-crowdsec-php

## Description: Create a watcher
## Usage: create-watcher login password
## Example: "ddev create-watcher watcherLogin watcherPassword"


LOGIN=${1:-watcherLogin}
PASSWORD=${2:-watcherPassword}


EXIST=$(cscli machines list -o raw | { grep "${LOGIN}" || true; })


if [ "$EXIST" ];
then
    cscli machines delete "$LOGIN" -o raw
fi

cscli machines add "$LOGIN" --password "$PASSWORD" -o raw
exit 0
