#!/usr/bin/env bash

#ddev-generated
# ddev manages this file and may delete or overwrite it unless the above line is removed.
# This file comes from "ddev get julienloizelet/ddev-crowdsec-php"

## Description: Configure CrowdSec and CrowdSec Bouncer
## Usage: crowdsec-config
## Example: "ddev crowdsec-config"

CHECKMULTISITE=$(ddev exec --raw -j grep MULTISITE wp-config-ddev.php | tail -1 | sed "s/define( 'MULTISITE',//g" | sed "s/);//g" | sed 's/ //g' | sed 's/\r//g'  | tail -1)

BOUNCER_KEY=$(ddev create-bouncer wordpress | sed 's/\r$//')
API_URL="https://crowdsec:8080"
echo "Bouncer created"
echo "Now setting ${BOUNCER_KEY} as CrowdSec_Bouncer Api key"
if [[ "$CHECKMULTISITE" == "true" ]]; then
  ddev wp network meta update 1 crowdsec_api_key "${BOUNCER_KEY}"
else
  ddev wp option set crowdsec_api_key "${BOUNCER_KEY}"
fi
echo "Now setting ${API_URL} as CrowdSec_Bouncer Api url"
if [[ "$CHECKMULTISITE" == "true" ]]; then
  ddev wp network meta update 1 crowdsec_api_url "${API_URL}"
else
  ddev wp option set crowdsec_api_url "${API_URL}"
fi

exit 0
